services:
  main-car:
    build:
      context: ./srcs/MainCar
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./srcs/MainCar
        target: /workspace
  controller:
    build:
      context: ./srcs/Controller
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./srcs/Controller
        target: /workspace
    depends_on:
      - main-car
  # dashboard:
  #   build:
  #     context: ./srcs/Dashboard
  #   command: /bin/bash
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - type: bind
  #       source: ./srcs/Dashboard
  #       target: /workspace
  #   depends_on:
  #     - main-car
  #     - controller
  # qt:
  #   build:
  #     context: ./srcs/Qt
  #   command: /bin/bash
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - type: bind
  #       source: ./srcs/Qt
  #       target: /workspace

